---
- name: download kubelet
  include_tasks: ../../download/tasks/download_file.yml
  vars:
    download: "{{ downloads.kubelet }}"
  run_once: true

- name: install kubelet
  copy:
    src: /vagrant/downloads/kubelet-{{ kube_version }}-amd64
    dest: /usr/local/bin/kubelet
    remote_src: true
    mode: "755"
    owner: root
    group: root

- name: download cni
  include_tasks: ../../download/tasks/download_file.yml
  vars:
    download: "{{ downloads.cni }}"
  run_once: true

- name: create /opt/cni/bin directory
  file:
    path: /opt/cni/bin
    state: directory

- name: install cni plugins
  unarchive:
    src: /vagrant/downloads/cni-plugins-linux-amd64-{{ cni_version }}.tgz
    dest: /opt/cni/bin
    remote_src: true

- name: download crictl
  include_tasks: ../../download/tasks/download_file.yml
  vars:
    download: "{{ downloads.crictl }}"
  run_once: true

- name: install crictl
  unarchive:
    src: /vagrant/downloads/crictl-{{ crictl_version }}-linux-amd64.tar.gz
    dest: /usr/local/bin
    remote_src: true

- name: copy kubelet.service
  template:
    src: kubelet.service.j2
    dest: /etc/systemd/system/kubelet.service

- name: copy kubelet.service.env (1/2)
  file:
    path: /etc/systemd/system/kubelet.service.d
    state: directory

- name: copy kubelet.service.env (2/2)
  template:
    src: 10-kubeadm.conf.j2
    dest: /etc/systemd/system/kubelet.service.d/10-kubeadm.conf

- name: enable kubelet
  systemd:
    name: kubelet.service
    daemon_reload: true
    state: started
    enabled: true
