---
- name: download containerd
  include_tasks: ../../download/tasks/download_file.yml
  vars:
    download: "{{ downloads.containerd }}"
  run_once: true

- name: install containerd
  unarchive:
    src: /vagrant/downloads/containerd-{{ containerd_version }}-linux-amd64.tar.gz
    dest: /usr/local/
    remote_src: true
  when: not ansible_check_mode

- name: generate containerd.service
  template:
    src: containerd.service.j2
    dest: /etc/systemd/system/containerd.service

- name: start containerd for the first time
  systemd:
    name: containerd
    state: started
    enabled: true
    daemon_reload: true

- name: ensure /etc/containerd directory is exists
  file:
    path: /etc/containerd/
    state: directory

- name: copy containerd config
  template:
    src: config.toml.j2
    dest: /etc/containerd/config.toml
  notify: restart containerd

- name: download nerdctl
  include_tasks: ../../download/tasks/download_file.yml
  vars:
    download: "{{ downloads.nerdctl }}"
  run_once: true

- name: install nerdctl
  unarchive:
    src: /vagrant/downloads/nerdctl-{{ nerdctl_version }}-linux-amd64.tar.gz
    dest: /usr/local/bin
    remote_src: true
