---
# tasks file for client
- name: Create kube config dir for current/ansible become user
  file:
    path: "{{ ansible_env.HOME | default('/root') }}/.kube"
    mode: "0700"
    state: directory

- name: Copy admin kubeconfig to current/ansible become user home
  copy:
    src: /etc/kubernetes/admin.conf
    dest: "{{ ansible_env.HOME | default('/root') }}/.kube/config"
    owner: "{{ ansible_env.USER | default('vagrant') }}"
    remote_src: true
    mode: "0600"
    backup: true
  delegate_to: "{{ groups['master'][0] }}"
  run_once: true
  become: true
