---
- block:
    - name: download | download file
      debug:
        msg: "{{ download.url }}"

    - name: download | Download item
      get_url:
        url: "{{ download.url }}"
        dest: "{{ download.dest }}"
        checksum: "{{ 'sha256:' + download.sha256 if download.sha256 else omit }}"
      delegate_to: localhost
      connection: local
      delegate_facts: false
      run_once: true
      become: false
      register: get_url_result
      until: "'OK' in get_url_result.msg or 'file already exists' in get_url_result.msg"
      retries: 4
      delay: "{{ retry_stagger | default(5) }}"

- name: download_file | Extract file archives
  include_tasks: extract_file.yml
  when: download.unarchive
