---
- name: extract_file | Unpacking archive
  unarchive:
    src: "{{ download.dest }}"
    dest: "{{ download.dest | dirname }}"
    copy: false
    extra_opts: "{{ download.unarchive_extra_opts | default(omit) }}"
