---
switch_mirror: true
ubuntu_apt_mirror: https://mirrors.tuna.tsinghua.edu.cn/ubuntu/
http_proxy: http://nexus.ddupan.top:3142/
upgrade_system: true
network_plugin: flannel
kube_version: v1.23.8

cluster_name: kubernetes
dns_domain: cluster.local
kube_service_addresses: 10.96.0.0/12
kube_pods_subnet: 10.244.0.0/16
kube_image_repo: k8s.gcr.io

crun_enabled: false

kube_utils:
  apt_install: false
  # keyring_url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
  keyring_url: https://mirrors.aliyun.com/kubernetes/apt/doc/apt-key.gpg
  # repository_url: https://apt.kubernetes.io/
  repository_url: https://mirrors.aliyun.com/kubernetes/apt/
# containerd_registries:
#    "docker.io":
#    - "https://registry-1.docker.io"
